openapi: "3.0.0"
info:
  title: Simple API overview
  version: 1.0.0
components:
  schemas:
    Success:
      description: The HTTP success response for operations on a specific object
      properties:
        id:
          description: The id of the object for which the API call resulted in a success
          type: string
      type: object
  securitySchemes:
    development - clientId:
      type: oauth2
      description: For more information, see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html
      flows:
        authorizationCode:
          authorizationUrl: https://<your domain>.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize
          tokenUrl: https://<your domain>.auth.ap-northeast-1.amazoncognito.com/oauth2/token
paths:
  /:
    get:
      operationId: listGet
      summary: List API versions
      security:
        - development - clientId: []
      responses:
        200:
          description: 200 response
          $ref: '#/components/schemas/Success'
          content:
            application/json:
